hello:
  world

spring:
  # redis
  redis:
    host: localhost
    port: 6379

# log
logging:
  config: classpath:logback-spring.xml
  level: debug

# dubbo
dubbo:
  application:
    name: stsm_consumer
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  consumer:
    timeout: 5000
  annotation:
    package: com.whut.stsm.web