hello:
  world

spring:
  # redis
  redis:
    host: localhost
    port: 6379

# log
logging:
  config: classpath:logback-spring.xml
  level: debug

# dubbo
dubbo:
  application:
    name: stsm_consumer
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  consumer:
    timeout: 5000
  annotation:
    package: com.whut.stsm.web

# http
http:
  # 允许访问的资源
  permitMvcMatcherUrls: /,/index,/webjars/**,/assets/**,/favicon.ico,/captcha
  login:
    loginPage: /login
    usernameParameter: username
    passwordParameter: password
    # 验证码参数
    captchaParameter: captcha
    # Session验证码参数
    sessionCaptchaParameter: sessionCaptcha
  logout:
    logoutUrl: /logout
    # 清除认证
    clearAuthentication: true
    # session失效
    invalidateHttpSession: true